apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: kibana-expose
spec:
  selector:
    app: kibana
  type: NodePort
  ports:
    - port: 443
      targetPort: 5601
      nodePort: 30001
